"""remove votes from blog

Revision ID: 530002d9eb1f
Revises: c1d36e42c30a
Create Date: 2021-03-17 11:42:26.919313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530002d9eb1f'
down_revision = 'c1d36e42c30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('body', sa.String(), nullable=True))
    op.drop_column('blogs', 'votes')
    op.drop_column('blogs', 'quote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('quote', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('votes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'body')
    # ### end Alembic commands ###
